### ISSUE TITLE
This library is not actually filtering by person, organization, place, etc.

### ISSUE THREAD

**Issue by EndBug** [cwrc/wikidata-entity-lookup#32]
This library claims to be filtering the results by type, but looking at the source code makes it evident that all methods just end up calling the same URL:
https://github.com/cwrc/wikidata-entity-lookup/blob/2cf36182f3c2f10ed02a9366c8e15a60bb00f36a/src/index.js#L9-L13

Was there ever a development version that was able to classify at least persons? I'm currently interested in identifying results based on whether they are people or not :)

**Comment by lucaju** [comment]
This library is deprecated and it will not be further developed. It was used internally by CWRC-Writer. It is now incorporate to CWRC-Writer newer version, named LEAF-Writer (see more here [https://gitlab.com/calincs/cwrc/leaf-writer/leaf-writer](https://gitlab.com/calincs/cwrc/leaf-writer/leaf-writer))

I suggest you use [Wikibase-SDK](https://github.com/maxlath/wikibase-sdk/tree/main) directly. It is very easy to use.

And you are right. It does not filter by entity type. The reason is that Wikibase-SDK does not have parameters to narrow the search to a specific entity type.

**Comment by EndBug** [comment]
Thanks for the info, I'll definitely check that out :)
